services:
  - type: web
    name: dezopay
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
